import { NextPage } from "next";
import Head from "next/head";
import MapComponent from "@/components/map";
import { Map } from "ol";

const Index: NextPage = () => {
  const mapIsReadyCallback = (map: Map) => {
    console.log(map);
  };
  return (
    <>
      <Head>
        <title>bantuin</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div className="relative">
        <MapComponent mapIsReadyCallback={mapIsReadyCallback} />
        <div className="absolute p-4 top-8 right-28 bg-slate-900 text-slate-200 rounded-xl">
          <div className="flex flex-col gap-2">
            <div className="bg-slate-700 px-2 py-1 text-xs">
              Telemetry:EMU-102
            </div>
            <div className="flex gap-2">
              <div className="flex flex-col">
                <div className="bg-slate-100 text-slate-800">Battery</div>
              </div>
              <div className="flex flex-col">
                <div className="bg-slate-100 text-slate-800">GPS</div>
              </div>
              <div className="flex flex-col">
                <div className="bg-slate-100 text-slate-800">Telemetry</div>
              </div>
              <div className="flex flex-col">
                <div className="bg-slate-100 text-slate-800">RC Link</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Index;
